Add Hangar and BuiltByBit pages to readme
PlaceholderAPI/PlaceholderAPI pull request #1006
Opened 2023-09-25 13:00 UTC by Andre601

## Pull Request

### Type

- [ ] Internal change (Doesn't affect end-user).
- [ ] External change (Does affect end-user).
- [ ] Wiki (Changes towards the [Wiki]).
- [x] Other: Updating README.md 

### Description

PlaceholderAPI is also available on Hangar (Paper's own plugins sharing platform) and BuiltByBit (formerly mc-market).
This PR adds those links to the readme to allow them to be found more easily. Maybe a announcement in the discussions tab should be made too to inform about the other platforms you can find PAPI on?

[Wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

2023-09-25 13:05 UTC, Funny-cube requested changes
small change

2023-09-25 13:05 UTC, Funny-cube commented on README.md
> +- [Build By Bit][bbb]
Should read 'BuiltByBit Page"

2023-09-25 13:13 UTC, Funny-cube approved these changes

2023-11-26 15:58 UTC, Andre601 commented
Will merge this now as I can't see why we should delay this small change any further and not promote the alternative download locations.

2023-11-26 15:58 UTC, merged