Fix #1034 & Deprecate VersionSpecific & update copyright
PlaceholderAPI/PlaceholderAPI pull request #1035
Opened 2024-01-26 13:48 UTC by PiggyPiglet

I don't code anymorethis was all @BlitzOffline

2024-01-26 13:51 UTC, Andre601 requested changes
Just a small thing to add for clarity

2024-01-26 13:51 UTC, Andre601 commented on src/main/java/me/clip/placeholderapi/expansion/VersionSpecific.java
>   */
```suggestion
 * @author Ryan McCarthy
 *
 * @deprecated Will be removed in a future release.
 */
```

2024-01-26 13:55 UTC, Andre601 approved these changes

2024-02-24 23:17 UTC, Andre601 commented
Anything stopping this from a merge?

2024-04-30 15:34 UTC, darbyjack approved these changes

2024-04-30 15:34 UTC, merged