Updated ThemePark
PlaceholderAPI/PlaceholderAPI pull request #475
Opened 2020-09-13 17:19 UTC by stijnb1234

## Pull Request

### Type
- [ ] Internal change (Doesn't affect end-user).
- [ ] External change (Does affect end-user).
- [x] Wiki (Changes towards the [Wiki]).
- [ ] Other: __________ 

### Description
Updated the ThemePark placeholders to v1.2 on eCloud.

[Wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

2020-09-13 17:19 UTC, stijnb1234 commented
My expansion is still not approved, so I added the url to the expansion.

2020-09-13 19:45 UTC, Andre601 requested changes

2020-09-13 19:45 UTC, Andre601 commented on wiki/Placeholders.md
> +> [Download here](https://api.extendedclip.com/expansions/themepark/)
Doesn't matter if it is yet approved or not. Just provide the command itself. People will be able to download it through multiple ways.
```suggestion
> /papi ecloud download themepark
```

2020-09-13 19:58 UTC, Andre601 approved these changes

2020-09-13 19:58 UTC, merged

2020-09-13 19:58 UTC, stijnb1234 commented
Changed. Any idea when my expansion will be approved? Its already waiting more then 5 months.

2020-09-13 19:59 UTC, Andre601 commented
There isn't an ETA on when those will be approved or denied.

@Funny-cube, @extendedclip and I think @darbyjack manage the eCloud so one of them has to approve/deny it.

2020-09-13 22:50 UTC, Funny-cube commented
Expansions are checked for verification upon request.

> If you've uploaded an expansion and wish for it to be verified contact us via our discord server.

In terms of the ThemePark expansions seems the author name and version in the expansion jar don't match what's listed on the eCloud, these should be matching to avoid any issues with update notifications and search.

2020-09-14 10:07 UTC, stijnb1234 commented
@Funny-cube That's fixed now. ;)