Folia support
PlaceholderAPI/PlaceholderAPI pull request #980
Opened 2023-06-26 00:12 UTC by Anon8281

## Pull Request

### Type

- [x] Internal change (Doesn't affect end-user).
- [ ] External change (Does affect end-user).
- [ ] Wiki (Changes towards the [Wiki]).
- [ ] Other: __________ 

### Description
Added Folia support using https://github.com/Anon8281/UniversalScheduler

2023-09-12 09:56 UTC, Emibergo02 commented
@PiggyPiglet @darbyjack are you considering to merge this PR?

2023-09-24 14:50 UTC, DarkyG2 commented
Been using it for a while and I have 0 issues with it on prod

2023-09-29 17:37 UTC, ewof commented
same had no issues after using for months

2023-10-27 22:54 UTC, xyfwdy commented
> same had no issues after using for months

+1

2023-11-28 09:13 UTC, Q2297045667 commented
Will this PR be supported in versions 1.20.3 and 1.21 in the future?

2024-01-21 09:38 UTC, Netherwhal commented
I am getting the following build error:

```
10:22:07 Could not determine the dependencies of task ':shadowJar'.
10:22:07 > Could not resolve all dependencies for configuration ':runtimeClasspath'.
10:22:07    > Could not find com.github.Anon8281:UniversalScheduler:0.1.3.
10:22:07      Searched in the following locations:
10:22:07        - https://oss.sonatype.org/content/repositories/snapshots/com/github/Anon8281/UniversalScheduler/0.1.3/UniversalScheduler-0.1.3.pom
10:22:07        - https://repo.maven.apache.org/maven2/com/github/Anon8281/UniversalScheduler/0.1.3/UniversalScheduler-0.1.3.pom
10:22:07        - file:/home/ec2-user/.m2/repository/com/github/Anon8281/UniversalScheduler/0.1.3/UniversalScheduler-0.1.3.pom
10:22:07        - https://repo.codemc.org/repository/maven-public/com/github/Anon8281/UniversalScheduler/0.1.3/UniversalScheduler-0.1.3.pom
10:22:07        - https://hub.spigotmc.org/nexus/content/repositories/snapshots/com/github/Anon8281/UniversalScheduler/0.1.3/UniversalScheduler-0.1.3.pom
10:22:07      Required by:
10:22:07          project :
```

2024-01-21 12:30 UTC, Andre601 requested changes

2024-01-21 12:30 UTC, Andre601 commented on build.gradle.kts
> +    implementation("com.github.Anon8281:UniversalScheduler:0.1.3")
This lib requires jitpack to be added as repository.

2024-01-21 17:41 UTC, Anon8281 commented
Sorry guys, forgot about repo

2024-01-21 21:26 UTC, Commandcracker commented
The TPS Calculation needs to change I recommend adding placeholders for 

- Lowest Region TPS
- Median Region TPS (I think this should replace normal server_tps on Folia)
- Highest Region TPS
- Player Region TPS
- (Maybe Specific Region TPS, but I don't think this is needed)

2024-01-21 21:31 UTC, iGabyTM commented
> The TPS Calculation needs to change I recommend adding placeholders for
> 
> * Lowest Region TPS
> * Median Region TPS (I think this should replace normal server_tps on Folia)
> * Highest Region TPS
> * Player Region TPS
> * (Maybe Specific Region TPS, but I don't think this is needed)

This should be part of a `folia` expansion, I don't think is worth to add extra placeholders in the server expansion that will be available only for folia.

2024-01-21 21:36 UTC, Commandcracker commented
> > The TPS Calculation needs to change I recommend adding placeholders for
> > 
> > * Lowest Region TPS
> > * Median Region TPS (I think this should replace normal server_tps on Folia)
> > * Highest Region TPS
> > * Player Region TPS
> > * (Maybe Specific Region TPS, but I don't think this is needed)
> 
> This should be part of a `folia` expansion, I don't think is worth to add extra placeholders in the server expansion that will be available only for folia.

If so, then I think the server_tps should be replaced with the Median Region TPS on Folia.
IDK what it currently returns, but it's probably always 0 or 20.

2024-01-21 21:55 UTC, Commandcracker commented
I tested it and the server_tps is always 20

2024-01-21 21:58 UTC, Commandcracker commented
Should I make an issue on Server-Expansion about the TPS when this PR is merged ?

2024-01-21 22:40 UTC, Andre601 approved these changes
Looks fine by me.

2024-05-31 09:03 UTC, HydrolienF commented
Is this merge request sill being reviewed ?
I would love to have an 1.20.6 Folia compatible PlaceholderAPI.

2024-08-01 13:49 UTC, Potenza7 commented
Folia dev 1.21 version has been released. Can you add 1.21 support?

2024-08-01 14:25 UTC, Anon8281 commented
> Folia dev 1.21 version has been released. Can you add 1.21 support?

Is there any issues running the current version of the plugin on 1.21?

2024-08-01 14:38 UTC, Potenza7 commented
> > Folia dev 1.21 version has been released. Can you add 1.21 support?
> 
> Is there any issues running the current version of the plugin on 1.21?

I made this comment without trying it. I just tried it and it works fine!

2024-10-14 15:20 UTC, ammodev commented
I know you still have pending reviews but is there a way of merging this soon™️?

2024-11-10 21:44 UTC, OoLunar commented
If you could merge this soon, that'd be appreciated! Everything seems fine by the glance of things?

2024-12-15 14:09 UTC, Panda260 commented
merge?

2025-01-22 08:37 UTC, TheBjoRedCraft commented
Any updates about merging?

2025-03-17 09:39 UTC, Ownercz commented
Any chance to get this merged please?

2025-04-17 11:06 UTC, StrangeOne101 commented
Only issue I had was PAPI passing a null player object to placeholder expansions. But other than that, works fine!

2025-04-25 17:39 UTC, liforra commented
when merge?

2025-06-16 03:22 UTC, Cartrigger commented
why isn't this merged?

2025-06-16 03:51 UTC, PiggyPiglet commented
Hi @Anon8281 

We can definitely look into merging this seeing as feedback is ultimately positive. One thing though, I'm not a huge fan of another dependency for security reasons. I'll be able to merge this if the implementation is built into PAPI

2025-07-01 12:25 UTC, PiggyPiglet commented
Merged in #1127

2025-07-01 12:25 UTC, closed without merging